@startuml
title Gestion des congés - Cas d'Utilisation
left to right direction

actor Administrateur as A
actor Employés as U


rectangle "Sprint 1" {
    usecase UC1 as "Demander un congé"
    usecase UC2 as "Voir tous les congés demandés"
    usecase UC3 as "Modifier un congé demandé"
    usecase UC4 as "Supprimer un congé demandé"
}

rectangle "Sprint 2" {
    usecase UC5 as "Voir toutes les congés des employés"

}

U --> UC1 : "Effectuer une demande"
U --> UC2 : "Consulter"
U --> UC3 : "Mettre à jour"
U --> UC4 : "Annuler"

A --> UC5 : "Consulter"

@enduml
